<a href="https://colab.research.google.com/github/illi0125/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [5]:
print(pd.__version__)

2.2.3

In [6]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
  'counts': [3, 7, 2, 8, 1, 9, 3]
}
print(mydataset)
print('========')

df = pd.DataFrame(mydataset)
print(df)

{'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Ford', 'BMW'], 'counts': [3, 7, 2, 8, 1, 9, 3]}
========
      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [7]:
df.head() # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [8]:
df.head(20) # 20 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [9]:
df.head(-1) # exclude last one

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9

In [10]:
df.head(0) # no rows only columns

Empty DataFrame
Columns: [cars, counts]
Index: []

In [11]:
df.tail() # default 5 rows from bottom

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [12]:
df.tail(100)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [13]:
df.tail(-1) # exclude first one

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [14]:
df.shape

(7, 2)

In [15]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [16]:
df.dtypes

cars      object
counts     int64
dtype: object

In [18]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [19]:
df.describe() # numerical columns only

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [20]:
df.describe(include="all")

       cars    counts
count     7  7.000000
unique    5       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  4.714286
std     NaN  3.199702
min     NaN  1.000000
25%     NaN  2.500000
50%     NaN  3.000000
75%     NaN  7.500000
max     NaN  9.000000

In [24]:
df.iloc[0] # select via indexes

cars      BMW
counts      3
Name: 0, dtype: object

In [22]:
df.iloc[2]

cars      Ford
counts       2
Name: 2, dtype: object

In [23]:
df.iloc[-1]

cars      BMW
counts      3
Name: 6, dtype: object

In [25]:
df.iloc[1:4]

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       8

In [26]:
df.iloc[1:5]

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [27]:
df.iloc[2:]

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [28]:
df.loc[:, "counts"]

0    3
1    7
2    2
3    8
4    1
5    9
6    3
Name: counts, dtype: int64

In [29]:
df.loc[:, "cars"]

0        BMW
1      Volvo
2       Ford
3      Tesla
4    Ferrari
5       Ford
6        BMW
Name: cars, dtype: object

In [30]:
df.loc[1, "counts"]

np.int64(7)

In [31]:
df.loc[2, "counts"]

np.int64(2)

In [32]:
df.loc[2, "cars"]

'Ford'

In [33]:
df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [34]:
df["counts"] > 3

0    False
1     True
2    False
3     True
4    False
5     True
6    False
Name: counts, dtype: bool

In [35]:
df[df["counts"] > 3]

    cars  counts
1  Volvo       7
3  Tesla       8
5   Ford       9

In [36]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [37]:
df[df["counts"] >= 3]

    cars  counts
0    BMW       3
1  Volvo       7
3  Tesla       8
5   Ford       9
6    BMW       3

In [38]:
df[df["counts"] != 3]

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9

In [39]:
df[df["counts"] < 3]

      cars  counts
2     Ford       2
4  Ferrari       1

In [40]:
df[df["counts"] <= 3]

      cars  counts
0      BMW       3
2     Ford       2
4  Ferrari       1
6      BMW       3

In [41]:
df[df["cars"] == "BMW"]

  cars  counts
0  BMW       3
6  BMW       3

In [42]:
df[df["cars"] == "Tesla"]

    cars  counts
3  Tesla       8

In [43]:
df[df["cars"] == "tesla"] # case sensitive

Empty DataFrame
Columns: [cars, counts]
Index: []

In [44]:
df.mean(numeric_only=True)

counts    4.714286
dtype: float64

In [45]:
df["counts"].mean()

np.float64(4.714285714285714)

In [46]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [47]:
df.min()

cars      BMW
counts      1
dtype: object

In [48]:
df.max()

cars      Volvo
counts        9
dtype: object

In [49]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [50]:
df.count()

cars      7
counts    7
dtype: int64

In [51]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [52]:
data_with_missing = {
  'cars': ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "BMW"],
  'counts': [3, 7, None, 2, 8, 1, None,]
}
print(data_with_missing)
print('========')

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

{'cars': ['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'BMW'], 'counts': [3, 7, None, 2, 8, 1, None]}
========
      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     2.0
4  Ferrari     8.0
5     None     1.0
6      BMW     NaN

In [53]:
df_missing.isnull()

    cars  counts
0  False   False
1  False   False
2   True    True
3  False   False
4  False   False
5   True   False
6  False    True

In [54]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [55]:
df_missing.dropna()

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     2.0
4  Ferrari     8.0

In [56]:
df_missing.dropna(how="all")

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     2.0
4  Ferrari     8.0
5     None     1.0
6      BMW     NaN

In [57]:
df_missing.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [58]:
df_missing.dropna(subset=["counts"])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     2.0
4  Ferrari     8.0
5     None     1.0

In [59]:
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     2.0
4  Ferrari     8.0
6      BMW     NaN

In [60]:
df_missing.fillna(0)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2        0     0.0
3    Tesla     2.0
4  Ferrari     8.0
5        0     1.0
6      BMW     0.0

In [61]:
df_missing.fillna("unknown")

      cars   counts
0      BMW      3.0
1    Volvo      7.0
2  unknown  unknown
3    Tesla      2.0
4  Ferrari      8.0
5  unknown      1.0
6      BMW  unknown

In [62]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     2.0
4  Ferrari     8.0
5  unknown     1.0
6      BMW     0.0

In [79]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [70]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [72]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.tail()

# df = pd.read_excel("Titanic-Dataset.xlsl")
# df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [74]:
df.to_excel("Titanic-Dataset.xlsx")

In [78]:
df.to_excel("test.xlsx")

In [80]:
df = pd.read_excel("test.xlsx")
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [81]:
# Series
cars = pd.Series(["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"])
print(cars)

0        BMW
1      Volvo
2       Ford
3      Tesla
4    Ferrari
5       Ford
6        BMW
dtype: object

In [82]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'BMW']